import { readFileSync, writeFileSync } from 'fs';

const FILE = process.env.FILE ?? '/home/jegger/workspace/UnitedEarth/data/Users.json';
const OUT  = process.env.OUT  ?? 'scripts/import-users.sql';

const raw = JSON.parse(readFileSync(FILE, 'utf-8'));
const entries = Object.entries(raw);

function escape(val) {
  if (val === null) return 'NULL';
  return `'${String(val).replace(/'/g, "''")}'`;
}

const lines = [
  '-- Generated by scripts/import-users.mjs',
  `-- Source: ${FILE}`,
  '',
];

let included = 0;
let skipped = 0;

for (const [id, u] of entries) {
  const isNewFmt = 'fN' in u || 'lN' in u || 'type' in u;

  if (isNewFmt && u.v === false) {
    lines.push(`-- skip unverified: ${id}`);
    skipped++;
    continue;
  }

  const email     = (u.email ?? u.e ?? '').trim().toLowerCase();
  const firstName = (u.firstName ?? u.fN ?? '').trim() || null;
  const lastName  = (u.lastName  ?? u.lN ?? '').trim() || null;
  const country   = (u.country   ?? u.c  ?? '').trim().toLowerCase();
  const language  = (u.lang      ?? u.l  ?? 'en').trim();
  const nlRaw     = u.emailNewsLetter ?? u.nL ?? 0;
  const newsletter = nlRaw > 0;

  let verifiedAt;
  if (isNewFmt && u.cd?._seconds) {
    verifiedAt = new Date(u.cd._seconds * 1000).toISOString();
  } else if (nlRaw > 0) {
    verifiedAt = new Date(nlRaw).toISOString();
  } else {
    verifiedAt = '2020-05-23T00:00:00.000Z';
  }

  if (!email) {
    lines.push(`-- skip no-email: ${id}`);
    skipped++;
    continue;
  }

  lines.push(
    `INSERT INTO supporters (type, first_name, last_name, country, language, email, newsletter, verified_at)` +
    ` VALUES ('p', ${escape(firstName)}, ${escape(lastName)}, ${escape(country)}, ${escape(language)}, ${escape(email)}, ${newsletter}, ${escape(verifiedAt)})` +
    ` ON CONFLICT (email) DO NOTHING;`
  );
  included++;
}

lines.push('', `-- total: ${included} inserts, ${skipped} skipped`);

writeFileSync(OUT, lines.join('\n') + '\n', 'utf-8');
console.log(`Written ${included} INSERT statements to ${OUT} (${skipped} skipped)`);
